export const FETCH_LESSON_REQUEST = 'lessons/FETCH_LESSON_REQUEST'
export const FETCH_LESSON_SUCCESS = 'lessons/FETCH_LESSON_SUCCESS'
export const FETCH_LESSON_ERROR = 'lessons/FETCH_LESSON_ERROR'

export const FETCH_LESSONS_REQUEST = 'lessons/FETCH_LESSONS_REQUEST'
export const FETCH_LESSONS_SUCCESS = 'lessons/FETCH_LESSONS_SUCCESS'
export const FETCH_LESSONS_ERROR = 'lessons/FETCH_LESSONS_ERROR'
