export const FETCH_TRAINIG_REQUEST = 'trainings/FETCH_TRAINIG_REQUEST'
export const FETCH_TRAINIG_SUCCESS = 'trainings/FETCH_TRAINIG_SUCCESS'
export const FETCH_TRAINIG_ERROR = 'trainings/FETCH_TRAINIG_ERROR'

export const FETCH_TRAINIGS_REQUEST = 'trainings/FETCH_TRAINIGS_REQUEST'
export const FETCH_TRAINIGS_SUCCESS = 'trainings/FETCH_TRAINIGS_SUCCESS'
export const FETCH_TRAINIGS_ERROR = 'trainings/FETCH_TRAINIGS_ERROR'
